version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: jvstock
      POSTGRES_PASSWORD: jvstock
      POSTGRES_DB: jvstock
    ports:
      - 5432:5432

volumes:
  postgres-data: